version: "3.8"

services:
  app:
    build: .
    container_name: yonudoo-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:latest
    container_name: yonudoo-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
